# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               JackCBT-7
tagline:             'JackC Blog'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://JackCBT7.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jack Cooper
  url:               http://JackCBT7.github.io

# Custom vars
version:             1.0.0
